/**
 * Native Chrome qualification for the byte-pinned structured-artifact review pair
 * generated by the exact native candidate under test.
 *
 * This is deliberately Chrome-only. The runner image owns the browser bytes and
 * the repository records the observed version in CI. These checks are automated
 * semantic accessibility and interaction assertions, not a full WCAG certification
 * and not evidence for Firefox, WebKit, Safari, or Edge-specific behavior. The
 * document itself is loaded from a file URL with JavaScript disabled.
 */
import { createHash } from "node:crypto";
import { readFile, realpath } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

import { expect, test } from "@playwright/test";

const repositoryRoot = path.resolve(process.cwd(), "..");
const configuredArtifactRoot = process.env.ARTIFACT_REVIEW_ROOT;
if (!configuredArtifactRoot) {
  throw new Error("ARTIFACT_REVIEW_ROOT must identify freshly generated candidate output");
}
const artifactRoot = path.resolve(configuredArtifactRoot);
const artifactRootReal = await realpath(artifactRoot);
const qualification = JSON.parse(
  await readFile(
    path.join(repositoryRoot, "docs", "artifacts", "browser-qualification.json"),
    "utf8",
  ),
) as {
  artifacts: Record<string, { path: string; sha256: string }>;
  viewports: Array<{ name: string; width: number; height: number }>;
};

const digest = (bytes: Buffer) => createHash("sha256").update(bytes).digest("hex");
const escapesRoot = (relative: string) =>
  path.isAbsolute(relative) || /^\.\.(?:[/\\]|$)/u.test(relative);

for (const [artifact, identity] of Object.entries(qualification.artifacts)) {
  for (const viewport of qualification.viewports) {
    test(`${artifact} is locally reviewable at ${viewport.name}`, async ({ browser }) => {
      const artifactPath = path.resolve(artifactRoot, identity.path);
      const lexicalRelative = path.relative(artifactRoot, artifactPath);
      if (escapesRoot(lexicalRelative)) {
        throw new Error(`qualification path escapes artifact root: ${identity.path}`);
      }
      const artifactPathReal = await realpath(artifactPath);
      const realRelative = path.relative(artifactRootReal, artifactPathReal);
      if (escapesRoot(realRelative)) {
        throw new Error(`qualification path resolves outside artifact root: ${identity.path}`);
      }
      const bytes = await readFile(artifactPathReal);
      expect(digest(bytes)).toBe(identity.sha256);

      const context = await browser.newContext({
        javaScriptEnabled: false,
        viewport: { width: viewport.width, height: viewport.height },
      });
      const page = await context.newPage();
      const remoteRequests: string[] = [];
      page.on("request", (request) => {
        if (/^https?:/u.test(request.url())) remoteRequests.push(request.url());
      });

      await page.goto(pathToFileURL(artifactPathReal).href, {
        waitUntil: "load",
      });
      expect(new URL(page.url()).protocol).toBe("file:");
      expect(remoteRequests).toEqual([]);
      const embeddedBrand = page.locator('aside img[alt="codeArbiter"]');
      await expect(embeddedBrand).toHaveJSProperty("complete", true);
      expect(
        await embeddedBrand.evaluate((image: HTMLImageElement) => image.naturalWidth),
      ).toBeGreaterThan(0);
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);

      const semantics = await page.evaluate(() => {
        const headings = Array.from(document.querySelectorAll("h1,h2,h3,h4,h5,h6"));
        const levels = headings.map((heading) => Number(heading.tagName.slice(1)));
        const headingJump = levels.some((level, index) => index > 0 && level > levels[index - 1] + 1);
        const ids = Array.from(document.querySelectorAll<HTMLElement>("[id]")).map((element) => element.id);
        return {
          lang: document.documentElement.lang,
          title: document.title.trim(),
          mainCount: document.querySelectorAll("main").length,
          h1Count: document.querySelectorAll("h1").length,
          headingJump,
          duplicateIds: ids.filter((id, index) => ids.indexOf(id) !== index),
          unnamedImages: Array.from(document.images).filter((image) => !image.hasAttribute("alt")).length,
          unnamedLinks: Array.from(document.links).filter((link) => !link.textContent?.trim() && !link.getAttribute("aria-label")).length,
          unnamedSummaries: Array.from(document.querySelectorAll("summary")).filter((summary) => !summary.textContent?.trim()).length,
          remoteLinks: Array.from(document.links).map((link) => link.href).filter((href) => /^https?:/u.test(href)),
        };
      });
      expect(semantics.lang).toBe("en");
      expect(semantics.title).not.toBe("");
      expect(semantics.mainCount).toBe(1);
      expect(semantics.h1Count).toBe(1);
      expect(semantics.headingJump).toBe(false);
      expect(semantics.duplicateIds).toEqual([]);
      expect(semantics.unnamedImages).toBe(0);
      expect(semantics.unnamedLinks).toBe(0);
      expect(semantics.unnamedSummaries).toBe(0);
      expect(semantics.remoteLinks).toEqual([]);

      const disclosures = page.locator("details > summary");
      if (artifact === "plan") expect(await disclosures.count()).toBeGreaterThan(0);
      const keyboardTarget = (await disclosures.count()) > 0
        ? disclosures.first()
        : page.locator("a.skip");
      await keyboardTarget.focus();
      await expect(keyboardTarget).toBeFocused();
      if ((await disclosures.count()) > 0) {
        const initiallyOpen = await keyboardTarget.locator("..").evaluate(
          (details: HTMLDetailsElement) => details.open,
        );
        await page.keyboard.press("Enter");
        expect(await keyboardTarget.locator("..").evaluate(
          (details: HTMLDetailsElement) => details.open,
        )).toBe(!initiallyOpen);
      }

      await page.evaluate(() => {
        const selectors = "p,li,td,th,summary,h1,h2,h3,h4,code,pre,.deck";
        for (const element of Array.from(document.querySelectorAll<HTMLElement>(selectors))) {
          element.style.fontSize = `${Number.parseFloat(getComputedStyle(element).fontSize) * 2}px`;
        }
      });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);

      await page.emulateMedia({ media: "print" });
      const hiddenDisclosureBodies = await page.locator("details > :not(summary)").evaluateAll((elements) =>
        elements.filter((element) => {
          const style = getComputedStyle(element);
          return style.display === "none" || element.getBoundingClientRect().height === 0;
        }).length,
      );
      expect(hiddenDisclosureBodies).toBe(0);
      expect(remoteRequests).toEqual([]);
      await context.close();
    });
  }
}
