import { escape as h, sourceHref, relations, type Atlas, type AtlasView } from './atlas-model';
const wrap = (text:string,width=42):string[] => {
  const out:string[]=[]; let line='';
  for (const word of text.split(/\s+/)) {
    if (word.length>width) { if(line) out.push(line); line=''; for(let i=0;i<word.length;i+=width) out.push(word.slice(i,i+width)); }
    else if (line.length+word.length+1>width) {out.push(line);line=word;} else line+=(line?' ':'')+word;
  }
  if(line) out.push(line); return out;
};
const text = (lines:string[],x:number,y:number,size=17) => lines.map((line,i)=>`<text x="${x}" y="${y+i*(size+7)}" font-size="${size}">${h(line)}</text>`).join('');
/** Vector geometry is presentation only. Non-adjacent handoffs are explicit
 * numbered continuations, never lines routed through someone else's text. */
export function renderAtlasSvg(view:AtlasView):string {
  const heading=wrap(view.title,67),boundary=wrap(view.boundary,126);
  const boundaryY=55+heading.length*34;
  const parts:string[]=[]; const nodeNumbers = new Map<string,number>(); let number=0,y=boundaryY+boundary.length*23+40;
  const nodeIds = new Set(view.chapters.flatMap(c=>c.nodes.map(n=>n.id)));
  for(const chapter of view.chapters) {
    const chapterTitle=wrap(chapter.title,74);parts.push(text(chapterTitle,36,y,24)); y+=chapterTitle.length*31+8;
    for(let start=0;start<chapter.nodes.length;start+=3) {
      const row=chapter.nodes.slice(start,start+3);
      const height=Math.max(...row.map(node=>80+wrap(node.title,28).length*27+wrap(`${node.detail} Returns: ${node.output}`,39).length*24));
      for(const [col,node] of row.entries()) {
        number++;nodeNumbers.set(node.id,number); const x=36+col*388;
        const titles=wrap(node.title,28),lines=wrap(`${node.detail} Returns: ${node.output}`,39);
        parts.push(`<a id="svg-${h(view.id)}-${h(node.id)}" href="${h(sourceHref(view.sources[node.source]))}" target="_blank" rel="noopener"><g class="node ${h(node.kind)}"><title>${h(node.title)}. ${h(node.output)}</title><rect x="${x}" y="${y}" width="356" height="${height}" rx="12"/>${text([`${String(number).padStart(2,'0')} / ${node.kind.toUpperCase()}${node.conditional?' / IF APPLICABLE':''}`],x+18,y+30,12)}${text(titles,x+18,y+62,20)}${text(lines,x+18,y+78+titles.length*27,16)}</g></a>`);
        const next=row[col+1];
        const edge=next && view.edges.find(edge=>edge.from===node.id&&edge.to===next.id);
        if(edge) parts.push(`<path class="edge ${h(edge.kind)}" d="M ${x+358} ${y+height/2} h 25" marker-end="url(#arrow-${h(view.id)})"/><title>${h(edge.label)}</title>`);
      }
      y+=height+26;
    }
    y+=20;
  }
  if(view.edges.length) {
    parts.push(text(['Directed handoffs and return paths'],36,y,24)); y+=42;
    for(const edge of view.edges) {
      if(!nodeIds.has(edge.from)||!nodeIds.has(edge.to)) throw new Error('Unknown SVG endpoint');
      const lines=wrap(`${nodeNumbers.get(edge.from)} → ${nodeNumbers.get(edge.to)} · ${relations[edge.kind]} · ${edge.label}. ${edge.detail}`,124);
      parts.push(`<a href="${h(sourceHref(view.sources[edge.source]))}">${text(lines,44,y,15)}</a>`);y+=lines.length*22+16;
    }
  }
  y+=35;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="${y}" viewBox="0 0 1200 ${y}" role="img" class="ca-atlas-vector" aria-labelledby="atlas-title-${h(view.id)} atlas-desc-${h(view.id)}"><title id="atlas-title-${h(view.id)}">${h(view.title)}</title><desc id="atlas-desc-${h(view.id)}">${h(view.boundary)} ${h(view.outcome)}</desc><style>.ca-atlas-vector{background:var(--ca-bg,#111720);color:var(--ca-ink,#edf1f6);font-family:var(--ca-font-sans,system-ui,sans-serif)}.ca-atlas-vector text{fill:currentColor}.ca-atlas-vector a{color:inherit}.ca-atlas-vector .node rect{fill:var(--ca-bg-raised,#1a2330);stroke:var(--ca-line-strong,#607187);stroke-width:1.5}.ca-atlas-vector .node.gate rect{stroke:var(--ca-brand,#d9ae5a);stroke-width:2}.ca-atlas-vector .node.context rect{stroke-dasharray:6 4}.ca-atlas-vector .edge{fill:none;stroke:#aabbcc;stroke-width:2}.ca-atlas-vector .edge.context,.ca-atlas-vector .edge.conditional,.ca-atlas-vector .edge.reuse{stroke-dasharray:5 4}@media(forced-colors:active){.ca-atlas-vector{background:Canvas;color:CanvasText}.ca-atlas-vector .node rect{fill:Canvas;stroke:CanvasText}.ca-atlas-vector .edge{stroke:CanvasText}}.ca-atlas-vector a:focus rect{stroke:currentColor;stroke-width:4}</style><defs><marker id="arrow-${h(view.id)}" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M 0 0 L 10 5 L 0 10 Z" fill="#aabbcc"/></marker></defs>${text(heading,36,46,27)}${text(boundary,36,boundaryY,16)}${parts.join('')}</svg>`;
}
const entryHash=(id:string)=>`atlas-${id}`;
export function renderAtlasHtml(atlas:Atlas,base='',offline=false):string {
  if (!/^(\/[A-Za-z0-9_-]+)*$/.test(base)) throw new Error('Invalid atlas site base');
  const assets=`${offline?'https://codearbiter.dev':base}/workflow-atlas/${atlas.reviewedAt}/`;
  const docBase=offline?'https://codearbiter.dev':base;
  const sources=(view:AtlasView,ids:string[])=>[...new Set(ids)].map(id=>`<a href="${h(sourceHref(view.sources[id]))}">Source: ${h(id)} @ ${view.sources[id].revision.slice(0,8)}</a>`).join(' · ');
  const viewLinks=(ids:string[])=>ids.map(id=>`<a href="#atlas-view-${h(id)}" data-atlas-link>${h(atlas.views.find(view=>view.id===id)!.title)}</a>`).join('');
  const buttons=['feature','fix','sprint','init','tribunal','release'].filter(id=>atlas.entries.some(e=>e.id===id)).map(id=>`<a class="ca-atlas-choice" href="#${entryHash(id)}" data-atlas-link>/${h(id)}</a>`).join('');
  const options=['core','advanced','alias','internal','deprecated'].map(group=>`<optgroup label="${group}">${atlas.entries.filter(e=>e.visibility===group).map(e=>`<option value="${h(e.id)}">/${h(e.id)}${e.replacement?` → ${h(e.replacement)}`:''}</option>`).join('')}</optgroup>`).join('');
  const entries=atlas.entries.map(entry=>`<details class="ca-atlas-entry" id="${entryHash(entry.id)}" data-atlas-entry="${h(entry.id)}" data-views="${h(entry.views.join(' '))}"><summary><span>/${h(entry.id)}</span><small>${h(entry.visibility)} · ${h(entry.workflow)}</small></summary><div class="ca-atlas-entry-body"><p>${h(entry.description)}</p>${entry.replacement?`<p><strong>Compatibility destination:</strong> ${h(entry.replacement)}. Keep this submode when continuing.</p>`:''}${entry.visibility==='internal'?'<p>This is an internal protocol, not a normal public command choice.</p>':''}<dl class="ca-atlas-hosts">${Object.entries(entry.invocations).map(([host,form])=>`<div data-atlas-host="${h(host)}"><dt>${h(host)}</dt><dd>${form?`<code>${h(form)}</code>`:'Not exposed on this host'}</dd></div>`).join('')}</dl><p>Entry availability does not qualify every typed workflow. <a href="${docBase}/guides/review-artifacts/#check-your-hosts-authority-capability">Check installed-host authority</a>.</p><p><a href="${docBase}/reference/commands/${h(entry.id)}/">Read the exact procedure</a> · <a href="${h(sourceHref(entry.source))}">Owning command source</a></p><div class="ca-atlas-related">${viewLinks(entry.views)}</div>${entry.views.length?'':'<p>The catalog locates this entry; its exact procedure is in the reference. A catalog group is not an execution path.</p>'}</div></details>`).join('');
  const views=atlas.views.map(view=>`<details class="ca-atlas-view" id="atlas-view-${h(view.id)}" data-atlas-view="${h(view.id)}"${['context-layers','debug-fix','tribunal','review-delivery'].includes(view.id)?'':' data-pagefind-ignore="all"'}><summary>${h(view.title)}</summary><div class="ca-atlas-view-body"><p class="ca-atlas-boundary">${h(view.boundary)}</p><p><strong>Actual outcome:</strong> ${h(view.outcome)}</p><details class="ca-atlas-drawing" data-pagefind-ignore="all"><summary>Open the detailed vector map</summary><p>Read at full size or use the complete text path below. Dashed relationships retain their named conditions.</p><a data-astro-reload href="${assets}${h(view.id)}.svg">Open full-size SVG</a><div class="ca-atlas-svg-scroll" tabindex="0" role="region" aria-label="${h(view.title)} vector map">${offline ? renderAtlasSvg(view) : `<img loading="lazy" decoding="async" src="${assets}${h(view.id)}.svg" width="1200" alt="${h(view.title)}. The complete nodes and directed handoffs follow in text." />`}</div></details>${view.chapters.map(chapter=>`<section><h4>${h(chapter.title)}</h4>${chapter.question?`<p>${h(chapter.question)}</p>`:''}<ol class="ca-atlas-nodes" data-ca-layout="peers">${chapter.nodes.map(node=>`<li id="atlas-node-${h(view.id)}-${h(node.id)}"><p class="ca-atlas-kind">${h(node.kind)}${node.conditional?' · if applicable':''}</p><h5>${h(node.title)}</h5><p>${h(node.detail)}</p><p><strong>Returns:</strong> ${h(node.output)}</p>${node.checks?`<details><summary>Read the complete checks</summary><ol>${node.checks.map(check=>`<li>${h(check)}</li>`).join('')}</ol></details>`:''}<p class="ca-atlas-sources">${sources(view,[node.source])}${node.href?` · <a href="${docBase}${h(node.href)}">Procedure</a>`:''}</p></li>`).join('')}</ol>${chapter.output?`<p class="ca-atlas-boundary"><strong>Before continuing:</strong> ${h(chapter.output)}</p>`:''}</section>`).join('')}<section><h4>Handoffs, branches and returns</h4><ul class="ca-atlas-handoffs">${view.edges.map(edge=>{const from=view.chapters.flatMap(c=>c.nodes).find(n=>n.id===edge.from)!;const to=view.chapters.flatMap(c=>c.nodes).find(n=>n.id===edge.to)!;return `<li><strong>${h(relations[edge.kind])}:</strong> <a href="#atlas-node-${h(view.id)}-${h(edge.from)}">${h(from.title)}</a> → <a href="#atlas-node-${h(view.id)}-${h(edge.to)}">${h(to.title)}</a>. <strong>${h(edge.label)}.</strong> ${h(edge.detail)} <span class="ca-atlas-sources">${sources(view,[edge.source])}</span></li>`;}).join('')}</ul></section></div></details>`).join('');
  return `<ca-workflow-atlas class="ca-atlas not-content" aria-label="Workflow route explorer"><header><p class="ca-eyebrow">Workflow atlas</p><h3>Follow the request. See what comes back.</h3><p>Choose an entry to find its procedure, applicable maps, context inputs and stopping points. These controls only change what you read.</p><p class="ca-atlas-revision">Current-source catalog reviewed at <code>${atlas.reviewedAt.slice(0,12)}</code>. Existing chapter maps retain their individual source revisions. Tribunal roster: ${atlas.lensCount} cards.</p></header><nav class="ca-atlas-choices" aria-label="Common entries">${buttons}</nav><div class="ca-atlas-controls" hidden data-atlas-controls><label>All entries<select data-atlas-select><option value="">Choose an entry</option>${options}</select></label><label>Host spelling<select data-atlas-host-select><option value="all">All hosts</option>${Object.keys(atlas.entries[0].invocations).map(host=>`<option value="${h(host)}">${h(host)}</option>`).join('')}</select></label><button type="button" data-atlas-show-all>Show all reading paths</button><a href="#atlas-feature" data-atlas-permalink data-atlas-link>Link to this selection</a></div><nav class="ca-atlas-choices" aria-label="Cross-route views"><a href="#atlas-view-context-layers" data-atlas-link>Context layers</a><a href="#atlas-view-all-routes" data-atlas-link>All routes</a></nav><p role="status" class="ca-atlas-status" data-atlas-status></p><div class="ca-atlas-entries" data-pagefind-ignore="all">${entries}</div><div class="ca-atlas-views">${views}</div><footer><p><strong>Offline editions, same reviewed data:</strong> <a data-astro-reload href="${assets}atlas.html" download>Standalone HTML</a> · <a data-astro-reload href="${assets}reading-guide.html" download>Script-free reading guide</a> · <a data-astro-reload href="${assets}all-routes.svg" download>All-routes SVG</a> · <a data-astro-reload href="${assets}sources.json" download>Source ledger</a></p><p>Reading a route records no workflow progress, approval or execution. The procedure and installed host retain their actual gates.</p></footer></ca-workflow-atlas>`;
}
